server:
  port: 8888
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes: #数组形式
        - id: order-service  #路由唯一标识
          uri: lb://xdclass-order-service  #想要转发到的地址
          order: 1 #优先级，数字越小优先级越高
          predicates: #断言 配置哪个路径才转发
            - Path=/order-server/**
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1

      discovery:
        locator:
          enabled: true


    nacos:
      discovery:
        server-addr: 192.168.219.130:8848
